[package]
name = "shadowseek-extractor"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
epub = "2.1.3"
rtf-parser = "0.4.2"
textract = "0.1.0"
